version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    links:
      - php7

  php7:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html
    # command: >
    #   /bin/bash -c "apt update && apt install -y git zip unzip &&
    #   curl -sS https://getcomposer.org/installer | php &&
    #   mv composer.phar /usr/local/bin/composer &&
    #   adduser libreria su libreria &&
    #   composer install"
  vue:
    build: ./vue/.
    ports:
      - 8088:8080
    volumes:
      - ./vue/app:/app
    tty: true
