version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    links:
      - php7

  php7:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html

  elm:
    build: ./elm/.
    ports:
      - 8088:8000
    volumes:
      - ./elm/app:/app
    tty: true

